// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDReiXLKPMIMXNaossQWAAzympEBMGMOjA',
    appId: '1:1074602904262:web:8b34d5019fafafd294a5c7',
    messagingSenderId: '1074602904262',
    projectId: 'helper-banua',
    authDomain: 'helper-banua.firebaseapp.com',
    storageBucket: 'helper-banua.firebasestorage.app',
    measurementId: 'G-XXFBC8HB19',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOXy92B7XtEg0e1QGrRcrP5jQbIGAVIVs',
    appId: '1:1074602904262:android:8bf3a5be3c79db9394a5c7',
    messagingSenderId: '1074602904262',
    projectId: 'helper-banua',
    storageBucket: 'helper-banua.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRczOqOjycSTmymrOug1OpiUpQpLINW4',
    appId: '1:1074602904262:ios:2f86421051a13c8894a5c7',
    messagingSenderId: '1074602904262',
    projectId: 'helper-banua',
    storageBucket: 'helper-banua.firebasestorage.app',
    iosBundleId: 'com.example.helperBanua',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRczOqOjycSTmymrOug1OpiUpQpLINW4',
    appId: '1:1074602904262:ios:2f86421051a13c8894a5c7',
    messagingSenderId: '1074602904262',
    projectId: 'helper-banua',
    storageBucket: 'helper-banua.firebasestorage.app',
    iosBundleId: 'com.example.helperBanua',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDReiXLKPMIMXNaossQWAAzympEBMGMOjA',
    appId: '1:1074602904262:web:01c468d12b93d43694a5c7',
    messagingSenderId: '1074602904262',
    projectId: 'helper-banua',
    authDomain: 'helper-banua.firebaseapp.com',
    storageBucket: 'helper-banua.firebasestorage.app',
    measurementId: 'G-RLCZBG8MR0',
  );
}
